sudo: required
language: java
services:
- docker
env:
- CHANGE_MINIKUBE_NONE_USER=true
before_script:
- unset _JAVA_OPTIONS
- cd finish
- sudo mount --make-rshared /
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x kubectl
- sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
- wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
- chmod +x minikube
- sudo ln -s $(pwd)/minikube /usr/local/bin/minikube
- wget https://github.com/istio/istio/releases/download/1.0.5/istio-1.0.5-linux.tar.gz -q -O istio-linux.tar.gz
- tar -zxf istio-linux.tar.gz
- rm istio-linux.tar.gz
- cd `ls | grep istio-`
- sudo ln -s $(pwd)/bin/istioctl /usr/local/bin/istioctl
- sudo minikube start --vm-driver=none --bootstrapper=localkube
- echo $(pwd)
- kubectl apply -f install/kubernetes/helm/istio/templates/crds.yaml
- kubectl apply -f install/kubernetes/istio-demo.yaml
- kubectl get deployments -n istio-system
- sleep 180
- kubectl get deployments -n istio-system
- chmod +x ../scripts/travisTest.sh
- cd ../start
script:
- ../scripts/travisTest.sh
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: YWWBjdjIecQL+Sam5fLjsyHjj+6S5FtDoZtpEyRRQDrn6wYdw9reZG2kNSzDjrUynMeeZXQUXEDABCOMhEN7a7L0SXjMdyTJ68XW9Rd6PRN5seYBHJvDQv9w3EwcKz71h3IIDYr8pxKFga06Afn0L9dkSOEEPVemqfftdnOI4Mm8peQrXGHTWQaYwsMYZ5vVq+RMXtYHaaIExcme0qEN+TUuEC6RGk386Mj7c5iT2GQ6grfi0tODzRmebAm6nWTG2eSmB6CXL0h3ly0weqK71RLQX5RicMB8IIuACEQWf6+GpwmVB/chlc0Z6Axz5mFibUBMBCGucLyJxNpFDr+FoSIBu88PWAqlwQDe0Uv8Dfs+1ZXnlEPt6dHZ4JnXau0NqKEct6tLmKPOSS+Q4QF/lhOmfIlPTDM+UcztigkSEt8AaAX9tdwgk0R/yUgGhFy+BDqkyeL/iJfc6AhlthqBrLvr0cFRfoGG01hKMw9ua+addtR2GpXV0ne90yfgNyDaQkrLJ+TH4NqIK9Y3JhaV6lVsvxisC3dNIzULvtMi/x24Wp76GYN3UhkkB5zlk24ZBjAcU3vypa3uHxM9aQjjiJyhM13vZtrLI7lL2+MKz8vs1y61vo/oppSSOswzuULvgbXqUmEtO9NUdf2GwT8vJUMMNNv5lHvjq51Rn5pV3LM=
    on_success: never
    on_failure: always
branches:
  only:
  - master
