apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /api/name
        backend:
          serviceName: name-service
          servicePort: 9080
      - path: /api/ping/.*
        backend:
          serviceName: ping-service
          servicePort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: name-service
  labels:
    app: name
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name
      version: v1
  template:
    metadata:
      labels:
        app: name
        version: v1
    spec:
      containers:
      - name: name
        image: name:1.0-SNAPSHOT
        env:
        - name: GREETING
          value: "Hello from V1!"
        ports:
        - containerPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name
      version: v2
  template:
    metadata:
      labels:
        app: name
        version: v2
    spec:
      containers:
      - name: name
        image: name:1.0-SNAPSHOT
        env:
        - name: GREETING
          value: "Hi from V2..."
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  labels:
    app: ping
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: ping:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
