apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: name-v1
spec:
  destination:
    name: name-service
  precedence: 1
  match:
    request:
      headers:
        uri:
          prefix: "/api/name"
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: name-v2
spec:
  destination:
    name: name-service
  precedence: 2
  match:
    request:
      headers:
        uri:
          prefix: "/api/name"
        x-version:
          regex: "^.*v2.*$"
  route:
  - labels:
      version: v2
