apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory-virtual-service
spec:
  hosts:
  - "my-inventory.com"
  gateways:
  - inventory-gateway
  http:
  - match:
    - uri:
        prefix: /inventory
    route:
    - destination:
        port:
          number: 9081
        host: inventory-service
  - match:
    - uri:
        prefix: /system
    route:
    - destination:
        port:
          number: 9080
        host: system-service
